version: "3"
services:

  backendCartuchos:
    imagen: 
    restart: always
    build: Backend_Cartuchos/.
    ports:
      - 8083:8083
    enviroment:
      MYSQL_HOST: mysqlCartuchos
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
  
  frontendCartuchos:configs:
    build: vegafernando/frontend-despliegue:latest
    ports:
      - 80:80