name: Prueba Despliegue

on:
  push:
    branches:
      - master # Puedes ajustar las ramas según tu configuración

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Login Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Imagen Docker
        run: docker build -t vegafernando/frontend-despliegue:latest .

      - name: Push a Docker Hub
        run: docker push vegafernando/frontend-despliegue:latest


   